name: ${PROJECT}

services:
  portainer:
    # Version wird im Dockerfile festgelegt (FROM portainer/portainer-ce:<Version>).
    build: .
    user: "root:988"
    env_file: .env
    container_name: "portainer"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - net
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  net:
    name: cloudflare-net
    external: true

volumes:
  portainer_data:
