version: "3.9"

services:
  portainer:
    image: "portainer/portainer-ce:2.11.1-alpine"
    container_name: "portainer"
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.qxf.de`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  net:
    external:
      name: traefik_net

volumes:
  portainer_data:
